base_url = "https://notes.januswel.com"
title = "Notes"
description = "januswel's notes"
compile_sass = false
minify_html = true
generate_feeds = true
generate_sitemap = true
theme = "anemone"

taxonomies = [
    {name = "tags", feed = true, paginate_by = 10},
]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
author = "januswel"
author_url = "https://januswel.com"
list_pages = true
default_og_image = "og/default.png"
enable_search = false

header_nav = [
  { url = "/", name_en = "januswel's notes" },
]
